const express = require("express");
const router = express.Router();
const passport = require("passport");
const authController = require("../controllers/AuthController");
const { storage, upload } = require("./lib/multer");
const authenticateToken = require("../middleware/authenticateToken");
router.get("/signup", authController.signup);
router.get("/logout", authController.logout);
router.get("/restore-password", authController.restore_password);
router.post("/restore-password", authController.forgotPassword);
router.post("/cofirmOtp", authController.cofirmOtp);
router.post("/changePassword", authController.changePassword);
router.get("/google", passport.authenticate("google", { scope: ["profile", "email"] }));
router.get("/google/callback", authController.googleCallback);
router.get("/google/success", authController.success);
router.post("/register", upload.single("userImage"), authController.register);
router.post("/login/handleLogin", authController.login);
router.get("/login", authController.renderLogin);

module.exports = router;
